version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-stretch
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: install npm dependencies
          command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "$HOME/.npm"
      - run:
          name: test
          command: npm test
